// Code generated by cmd/gen-types; DO NOT EDIT.
package types

import (
	"errors"

	"database/sql/driver"
	"github.com/google/uuid"
)

type IDs interface {
	ChatID | EventID | FailedJobID | JobID | MessageID | ProblemID | RequestID | UserID
}

var ErrEmptyID = errors.New("empty id")

func Parse[t IDs](value string) (t, error) {
	id, err := uuid.Parse(value)
	if err != nil {
		return t{}, err
	}
	return t(id), nil
}

func MustParse[t IDs](value string) t {
	id, err := uuid.Parse(value)
	if err != nil {
		panic(err)
	}
	return t(id)
}

type ChatID uuid.UUID

var ChatIDNil = ChatID(uuid.Nil)

func NewChatID() ChatID {
	return ChatID(uuid.New())
}

func (id ChatID) String() string {
	return uuid.UUID(id).String()
}

func (id ChatID) Value() (driver.Value, error) {
	return uuid.UUID(id).Value()
}

func (id *ChatID) Scan(v any) error {
	return (*uuid.UUID)(id).Scan(v)
}

func (id ChatID) MarshalText() ([]byte, error) {
	return (uuid.UUID)(id).MarshalText()
}

func (id *ChatID) UnmarshalText(data []byte) error {
	return (*uuid.UUID)(id).UnmarshalText(data)
}

func (id ChatID) IsZero() bool {
	return id == ChatIDNil
}

func (id ChatID) Matches(other any) bool {
	return id == other
}

func (id ChatID) Validate() error {
	if id.IsZero() {
		return ErrEmptyID
	}
	return nil
}

type EventID uuid.UUID

var EventIDNil = EventID(uuid.Nil)

func NewEventID() EventID {
	return EventID(uuid.New())
}

func (id EventID) String() string {
	return uuid.UUID(id).String()
}

func (id EventID) Value() (driver.Value, error) {
	return uuid.UUID(id).Value()
}

func (id *EventID) Scan(v any) error {
	return (*uuid.UUID)(id).Scan(v)
}

func (id EventID) MarshalText() ([]byte, error) {
	return (uuid.UUID)(id).MarshalText()
}

func (id *EventID) UnmarshalText(data []byte) error {
	return (*uuid.UUID)(id).UnmarshalText(data)
}

func (id EventID) IsZero() bool {
	return id == EventIDNil
}

func (id EventID) Matches(other any) bool {
	return id == other
}

func (id EventID) Validate() error {
	if id.IsZero() {
		return ErrEmptyID
	}
	return nil
}

type FailedJobID uuid.UUID

var FailedJobIDNil = FailedJobID(uuid.Nil)

func NewFailedJobID() FailedJobID {
	return FailedJobID(uuid.New())
}

func (id FailedJobID) String() string {
	return uuid.UUID(id).String()
}

func (id FailedJobID) Value() (driver.Value, error) {
	return uuid.UUID(id).Value()
}

func (id *FailedJobID) Scan(v any) error {
	return (*uuid.UUID)(id).Scan(v)
}

func (id FailedJobID) MarshalText() ([]byte, error) {
	return (uuid.UUID)(id).MarshalText()
}

func (id *FailedJobID) UnmarshalText(data []byte) error {
	return (*uuid.UUID)(id).UnmarshalText(data)
}

func (id FailedJobID) IsZero() bool {
	return id == FailedJobIDNil
}

func (id FailedJobID) Matches(other any) bool {
	return id == other
}

func (id FailedJobID) Validate() error {
	if id.IsZero() {
		return ErrEmptyID
	}
	return nil
}

type JobID uuid.UUID

var JobIDNil = JobID(uuid.Nil)

func NewJobID() JobID {
	return JobID(uuid.New())
}

func (id JobID) String() string {
	return uuid.UUID(id).String()
}

func (id JobID) Value() (driver.Value, error) {
	return uuid.UUID(id).Value()
}

func (id *JobID) Scan(v any) error {
	return (*uuid.UUID)(id).Scan(v)
}

func (id JobID) MarshalText() ([]byte, error) {
	return (uuid.UUID)(id).MarshalText()
}

func (id *JobID) UnmarshalText(data []byte) error {
	return (*uuid.UUID)(id).UnmarshalText(data)
}

func (id JobID) IsZero() bool {
	return id == JobIDNil
}

func (id JobID) Matches(other any) bool {
	return id == other
}

func (id JobID) Validate() error {
	if id.IsZero() {
		return ErrEmptyID
	}
	return nil
}

type MessageID uuid.UUID

var MessageIDNil = MessageID(uuid.Nil)

func NewMessageID() MessageID {
	return MessageID(uuid.New())
}

func (id MessageID) String() string {
	return uuid.UUID(id).String()
}

func (id MessageID) Value() (driver.Value, error) {
	return uuid.UUID(id).Value()
}

func (id *MessageID) Scan(v any) error {
	return (*uuid.UUID)(id).Scan(v)
}

func (id MessageID) MarshalText() ([]byte, error) {
	return (uuid.UUID)(id).MarshalText()
}

func (id *MessageID) UnmarshalText(data []byte) error {
	return (*uuid.UUID)(id).UnmarshalText(data)
}

func (id MessageID) IsZero() bool {
	return id == MessageIDNil
}

func (id MessageID) Matches(other any) bool {
	return id == other
}

func (id MessageID) Validate() error {
	if id.IsZero() {
		return ErrEmptyID
	}
	return nil
}

type ProblemID uuid.UUID

var ProblemIDNil = ProblemID(uuid.Nil)

func NewProblemID() ProblemID {
	return ProblemID(uuid.New())
}

func (id ProblemID) String() string {
	return uuid.UUID(id).String()
}

func (id ProblemID) Value() (driver.Value, error) {
	return uuid.UUID(id).Value()
}

func (id *ProblemID) Scan(v any) error {
	return (*uuid.UUID)(id).Scan(v)
}

func (id ProblemID) MarshalText() ([]byte, error) {
	return (uuid.UUID)(id).MarshalText()
}

func (id *ProblemID) UnmarshalText(data []byte) error {
	return (*uuid.UUID)(id).UnmarshalText(data)
}

func (id ProblemID) IsZero() bool {
	return id == ProblemIDNil
}

func (id ProblemID) Matches(other any) bool {
	return id == other
}

func (id ProblemID) Validate() error {
	if id.IsZero() {
		return ErrEmptyID
	}
	return nil
}

type RequestID uuid.UUID

var RequestIDNil = RequestID(uuid.Nil)

func NewRequestID() RequestID {
	return RequestID(uuid.New())
}

func (id RequestID) String() string {
	return uuid.UUID(id).String()
}

func (id RequestID) Value() (driver.Value, error) {
	return uuid.UUID(id).Value()
}

func (id *RequestID) Scan(v any) error {
	return (*uuid.UUID)(id).Scan(v)
}

func (id RequestID) MarshalText() ([]byte, error) {
	return (uuid.UUID)(id).MarshalText()
}

func (id *RequestID) UnmarshalText(data []byte) error {
	return (*uuid.UUID)(id).UnmarshalText(data)
}

func (id RequestID) IsZero() bool {
	return id == RequestIDNil
}

func (id RequestID) Matches(other any) bool {
	return id == other
}

func (id RequestID) Validate() error {
	if id.IsZero() {
		return ErrEmptyID
	}
	return nil
}

type UserID uuid.UUID

var UserIDNil = UserID(uuid.Nil)

func NewUserID() UserID {
	return UserID(uuid.New())
}

func (id UserID) String() string {
	return uuid.UUID(id).String()
}

func (id UserID) Value() (driver.Value, error) {
	return uuid.UUID(id).Value()
}

func (id *UserID) Scan(v any) error {
	return (*uuid.UUID)(id).Scan(v)
}

func (id UserID) MarshalText() ([]byte, error) {
	return (uuid.UUID)(id).MarshalText()
}

func (id *UserID) UnmarshalText(data []byte) error {
	return (*uuid.UUID)(id).UnmarshalText(data)
}

func (id UserID) IsZero() bool {
	return id == UserIDNil
}

func (id UserID) Matches(other any) bool {
	return id == other
}

func (id UserID) Validate() error {
	if id.IsZero() {
		return ErrEmptyID
	}
	return nil
}
