# https://taskfile.dev
version: '3'

silent: true

vars:
  GO_MODULE: github.com/keepcalmist/chat-service
  GO_FILES:
    sh: find . -type f -name '*.go' -not -path "./vendor/*" -not -path "*.gen.go" | tr "\n" " "

  GOLANGCI_LINT_VERSION: v1.52.2
  GOLANGCI_LINT_CACHE:
    sh: echo "$HOME/Library/Caches"
  TOOLS_DIR:
    sh: "echo `pwd`/bin/tools"
  DEV_TOOLS: |
    github.com/daixiang0/gci@v0.10.1
    mvdan.cc/gofumpt@v0.4.0

tasks:
  default:
    cmds:
      - task: tidy
      - task: fmt
      - task: lint
      - task: tests
      - task: build

  tidy:
    - echo "- Tidy"
    - go mod tidy
    - task: vendor

  vendor:
    - echo "- Vendor"
    - go mod vendor

  fmt:
    dir: '{{.TOOLS_DIR}}'
    cmds:
    - echo "- Format"
    - gofumpt -l -w ../..
    - gci write -s standard -s default -s "prefix(github.com/keepcalmist/chat-service)" ../..

  lint:
    cmds:
      - echo "- Lint"
      - mkdir -p {{.GOLANGCI_LINT_CACHE}}
      - task: lint:cmd
        vars: {CLI_ARGS: "run -v --fix --timeout=5m ./..."}

  lint:cmd:
    cmds:
      - |
        docker run --rm \
          -v "$(pwd):/app" -w /app \
          -v "{{.GOLANGCI_LINT_CACHE}}:/root/.cache" \
          golangci/golangci-lint:{{.GOLANGCI_LINT_VERSION}} \
          golangci-lint {{.CLI_ARGS}}

  tests:
    cmds:
      - echo "- Tests"
      - go test -race ./...

  build:
    cmds:
      - echo "- Build"
      - go build -o ./bin/ ./cmd/chat-service

  dev-tools:install:
    cmds:
      - echo "- Install gci"
      - export GOBIN="{{.TOOLS_DIR}}" && go install github.com/daixiang0/gci@latest
      - echo "- Install gofumpt"
      - export GOBIN="{{.TOOLS_DIR}}" && go install mvdan.cc/gofumpt@latest
      - echo "- Install options-gen"
      - export GOBIN="{{.TOOLS_DIR}}" && go install github.com/kazhuravlev/options-gen/cmd/options-gen@latest     -

  generate:
    cmds:
      - export PATH="${PATH}:{{.TOOLS_DIR}}" && go generate ./...
    aliases: [gen]