// Code generated by options-gen. DO NOT EDIT.
package clientmessagesentjob

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
	"go.uber.org/zap"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	messageRepository messageRepository,
	eventStream eventStream,
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from field tag (if present)

	o.messageRepository = messageRepository
	o.eventStream = eventStream

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithLogger(opt *zap.Logger) OptOptionsSetter {
	return func(o *Options) {
		o.logger = opt
	}
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("messageRepository", _validate_Options_messageRepository(o)))
	errs.Add(errors461e464ebed9.NewValidationError("eventStream", _validate_Options_eventStream(o)))
	return errs.AsError()
}

func _validate_Options_messageRepository(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.messageRepository, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `messageRepository` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_eventStream(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.eventStream, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `eventStream` did not pass the test: %w", err)
	}
	return nil
}
