version: "3.8"

services:
  swagger-ui:
    container_name: swagger-ui
    image: swaggerapi/swagger-ui:v5.9.0
    profiles:
      - all
    ports:
      - "3011:8080"
    environment:
      URLS: '[
      {name:"client-apiv1", url:"swagger-client-apiv1.yml"},
      {name:"manager-apiv1", url:"swagger-manager-apiv1.yml"}
      ]'
    volumes:
      - ../../api/client.v1.swagger.yml:/usr/share/nginx/html/swagger-client-apiv1.yml
      - ../../api/manager.v1.swagger.yml:/usr/share/nginx/html/swagger-manager-apiv1.yml

