version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: chat-service
      POSTGRES_USER: chat-service
      POSTGRES_PASSWORD: chat-service
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgresql-data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "127.0.0.1:5432:5432"
    profiles:
      - psql

  keycloak:
    image: quay.io/keycloak/keycloak:21.0.2
    volumes:
      - ./dump.json:/opt/keycloak/data/import/Bank-realm.json
    command:
      - start-dev --import-realm
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_SCHEMA: public
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "127.0.0.1:3010:8080"
    profiles:
      - all

  zookeeper:
    image: zookeeper:3.8.0
    ports:
      - "127.0.0.1:2181:2181"
    profiles:
      - all

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "127.0.0.1:9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "chat.messages:16:1,afc.msg-verdicts:16:1,afc.msg-verdicts.dlq:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    profiles:
      - all

  afc_emulator:
    image: antonboom/writing-go-service.afc
    restart: on-failure
    environment:
      AFC_LOG_LEVEL: "DEBUG"
      AFC_BROKER_ADDR: kafka:29092
      AFC_MESSAGES_TOPIC: "chat.messages"
      AFC_VERDICTS_TOPIC: "afc.msg-verdicts"
      AFC_VERDICTS_SIGN_PRIVATE_KEY: |
        -----BEGIN RSA PRIVATE KEY-----
        MIICXQIBAAKBgQDVaE2fXyKjmTNOJaw/7k+qtJlIgyS+tFoJRXkoAUjqIcIp4K7U
        smcSvDnhXvhv+HdyZSVMXubkz16dIuf2dk7oLWKRwa4Jab0hFgWN+h8Ba1+mXHzM
        K1P/gtNiMOr4RRzjrQ9WOm6LfruFeIqFEfL/xCOe0uHqM3Wpf+wt5WjFuQIDAQAB
        AoGBAKkvC3qxfVCdf+MQUsJMN7RpgKvP7C2T5V08SpTAkAGtybRRf8j3tmdP+cMF
        +4cpP+jc7vjgs8Pp8mQ47BSkLmDIA4V+enCKwFw9lMi/PEjKSu5bcDYn/SCWtMR9
        tp7qtTSNZpK6Ei1wcXnXd7NdVzRh8SgG++IyP9K5oEtsSXlBAkEA73wy7B7exFGV
        D9UkHo/R3UdbE35whT2HLA2ozzMnQfGlW40ocp/6Abhc0NKZDyZQJJTHhEOa2VUr
        LN8AxhN4JQJBAOQfvGIGh24hx/0yX3iOVpDvMpkJ8GQ5UA36+1Xgl1tnywcXeUhO
        Fn3JTTr58+i7S1GP2zBnq7y9oN38JHyrqQUCQFquvNmMFu5ftgH4w2SPMPiJPIN1
        LUZGthiIU5Oh2wutZN/144sD6LceCIdKN4r1BwPTEnmS39/L0D19c92NIcECQQC9
        w9ycmpvMNJO9f0rF6Xn/ZMttXUQ4yyhaCN9Mx+CAq+3LP26nhDXXez4ggk6w2iTE
        e2u1b3gAMKqCHr5naxDVAkAw/nkfpoi/dTU0hKsFtPXAZbVkhGI4liFtzdJd5R9O
        X/IxeJPJYn1QCwvzqim5xOVX7DCYUuFApT6TEbeaNA3m
        -----END RSA PRIVATE KEY-----

volumes:
  postgresql-data:
