// Package clientevents provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package clientevents

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/keepcalmist/chat-service/internal/types"
	"github.com/oapi-codegen/runtime"
)

// Event defines model for Event.
type Event struct {
	// EventType Тип события.
	EventType string `json:"eventType"`
	union     json.RawMessage
}

// MessageBlockedEvent defines model for MessageBlockedEvent.
type MessageBlockedEvent = MessageId

// MessageId defines model for MessageId.
type MessageId struct {
	// EventId Идентификатор события.
	EventId types.EventID `json:"eventId"`

	// MessageId Идентификатор сообщения.
	MessageId types.MessageID `json:"messageId"`

	// RequestId Идентификатор запроса.
	RequestId types.RequestID `json:"requestId"`
}

// MessageSentEvent defines model for MessageSentEvent.
type MessageSentEvent = MessageId

// NewMessageEvent defines model for NewMessageEvent.
type NewMessageEvent struct {
	// AuthorId Идентификатор автора события.
	AuthorId *types.UserID `json:"authorId,omitempty"`

	// Body Тело события.
	Body string `json:"body"`

	// CreatedAt Дата создания события.
	CreatedAt time.Time `json:"createdAt"`

	// EventId Идентификатор события.
	EventId types.EventID `json:"eventId"`

	// IsService Является ли событие системным.
	IsService bool `json:"isService"`

	// MessageId Идентификатор сообщения.
	MessageId types.MessageID `json:"messageId"`

	// RequestId Идентификатор запроса.
	RequestId types.RequestID `json:"requestId"`
}

// AsMessageSentEvent returns the union data inside the Event as a MessageSentEvent
func (t Event) AsMessageSentEvent() (MessageSentEvent, error) {
	var body MessageSentEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMessageSentEvent overwrites any union data inside the Event as the provided MessageSentEvent
func (t *Event) FromMessageSentEvent(v MessageSentEvent) error {
	t.EventType = "MessageSentEvent"

	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMessageSentEvent performs a merge with any union data inside the Event, using the provided MessageSentEvent
func (t *Event) MergeMessageSentEvent(v MessageSentEvent) error {
	t.EventType = "MessageSentEvent"

	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsMessageBlockedEvent returns the union data inside the Event as a MessageBlockedEvent
func (t Event) AsMessageBlockedEvent() (MessageBlockedEvent, error) {
	var body MessageBlockedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMessageBlockedEvent overwrites any union data inside the Event as the provided MessageBlockedEvent
func (t *Event) FromMessageBlockedEvent(v MessageBlockedEvent) error {
	t.EventType = "MessageBlockedEvent"

	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMessageBlockedEvent performs a merge with any union data inside the Event, using the provided MessageBlockedEvent
func (t *Event) MergeMessageBlockedEvent(v MessageBlockedEvent) error {
	t.EventType = "MessageBlockedEvent"

	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsNewMessageEvent returns the union data inside the Event as a NewMessageEvent
func (t Event) AsNewMessageEvent() (NewMessageEvent, error) {
	var body NewMessageEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNewMessageEvent overwrites any union data inside the Event as the provided NewMessageEvent
func (t *Event) FromNewMessageEvent(v NewMessageEvent) error {
	t.EventType = "NewMessageEvent"

	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNewMessageEvent performs a merge with any union data inside the Event, using the provided NewMessageEvent
func (t *Event) MergeNewMessageEvent(v NewMessageEvent) error {
	t.EventType = "NewMessageEvent"

	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsMessageId returns the union data inside the Event as a MessageId
func (t Event) AsMessageId() (MessageId, error) {
	var body MessageId
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMessageId overwrites any union data inside the Event as the provided MessageId
func (t *Event) FromMessageId(v MessageId) error {
	t.EventType = "MessageId"

	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMessageId performs a merge with any union data inside the Event, using the provided MessageId
func (t *Event) MergeMessageId(v MessageId) error {
	t.EventType = "MessageId"

	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t Event) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"eventType"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t Event) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "MessageBlockedEvent":
		return t.AsMessageBlockedEvent()
	case "MessageId":
		return t.AsMessageId()
	case "MessageSentEvent":
		return t.AsMessageSentEvent()
	case "NewMessageEvent":
		return t.AsNewMessageEvent()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t Event) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	object["eventType"], err = json.Marshal(t.EventType)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'eventType': %w", err)
	}

	b, err = json.Marshal(object)
	return b, err
}

func (t *Event) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["eventType"]; found {
		err = json.Unmarshal(raw, &t.EventType)
		if err != nil {
			return fmt.Errorf("error reading 'eventType': %w", err)
		}
	}

	return err
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xXwW7bRhD9FWJaoBdaVNpLwFsTF4VQJAbq9hT4sCJH4sbkLrs7lGsYBGKjlyIHX3ro",
	"uT9QNYgQoU6UXxj+UbFLKZJtopVODQKdPF7Ozrz39g20ewGJLkqtUJGF+AJskmEhfPjNBBW5IJU2MbKQ",
	"SpA2bqE0ukRD509FgRADusQfzkuEOgSt8GgE8bML+NzgCGL4LFp3iJbloydorRjjMSpq29ThVhse5To5",
	"xXS7PU/xbLltpx6DFOqTcEVSohdjzdEJgk6QkqRWEAP/wXN+HzSXvOC/mpfNFc+b6x6EQD4dLBmpxlDX",
	"IRj8qZIGU4ifbVQM23iQQpuB1sUndQhdrNf6b0IbpB3AfufXPON3HtEvPOe/edpc8aJ50QF2pE0hCGKo",
	"KpneAx/CzwdjfSCLUpsWgqAMYhhLyqphL9FFdIpYJiIvpKUoyQQdWDQTmWAkFaFRIo9cSes84mstG/jF",
	"nqc2OHQfiw+nsDMhR+lXl/BxkFr5ydNaH+wutPgNT/l984IXzSVP/39K3y9ZHHbb+Y6FNw/z5ANUPXyO",
	"iZtGeLJ51HtT7039CZl6/dO29/be25+It+/eqOILEHm+/X3PXa3Cu+MgKsq02VXnKb9qQ55+dMPxo0XT",
	"mmio0/POG+OMb3jx33fGEBKDgjD9mjrK/OblWPJ/w6952k7SvwmSCsIDkgV2NZP2uKXZ0exPfsU3zTXP",
	"mqvmsrkO+IbntxrxzP07by6bK57xW37XvOS3G5yGWuco1D0jeo02iW7iuO/Ck9oVkGqkHUiSlLuvj4Q6",
	"DY6r0p1o8DgTFDzOJSoKvFEthDBBY1sqkwf+oVKiEqWEGL7qPej1IfQu8I6MLFVDF4yxQ/YBBZVFG4y0",
	"Ccao0AiSahz4ebK94IgyNGfSYiApSDVa9QU5FZzlhSvhnA7fIh27Jk4KW2pl21n4st93fxKtaDVfZZnL",
	"xG+MnlsHYPVI2376ls+fVrnbZI6+g7r2687gaKwvdjvnECeY67JwcrZZEEJlcojhzMZRlOtE5Jm2FD/s",
	"P+xHZ9a1+icAAP//2ekE+VkOAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
