// Package clientevents provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package clientevents

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/keepcalmist/chat-service/internal/types"
	"github.com/oapi-codegen/runtime"
)

// AllEventsHaveFields defines model for AllEventsHaveFields.
type AllEventsHaveFields struct {
	// EventId Идентификатор события.
	EventId types.EventID `json:"eventId"`

	// EventType Тип события.
	EventType string `json:"eventType"`

	// MessageId Идентификатор сообщения.
	MessageId types.MessageID `json:"messageId"`

	// RequestId Идентификатор запроса.
	RequestId types.RequestID `json:"requestId"`
}

// Event defines model for Event.
type Event struct {
	union json.RawMessage
}

// MessageBlockedEvent defines model for MessageBlockedEvent.
type MessageBlockedEvent struct {
	// EventId Идентификатор события.
	EventId types.EventID `json:"eventId"`

	// EventType Тип события.
	EventType string `json:"eventType"`

	// MessageId Идентификатор сообщения.
	MessageId types.MessageID `json:"messageId"`

	// RequestId Идентификатор запроса.
	RequestId types.RequestID `json:"requestId"`
}

// MessageId defines model for MessageId.
type MessageId struct {
	// EventId Идентификатор события.
	EventId types.EventID `json:"eventId"`

	// EventType Тип события.
	EventType string `json:"eventType"`

	// MessageId Идентификатор сообщения.
	MessageId types.MessageID `json:"messageId"`

	// RequestId Идентификатор запроса.
	RequestId types.RequestID `json:"requestId"`
}

// MessageSentEvent defines model for MessageSentEvent.
type MessageSentEvent struct {
	// EventId Идентификатор события.
	EventId types.EventID `json:"eventId"`

	// EventType Тип события.
	EventType string `json:"eventType"`

	// MessageId Идентификатор сообщения.
	MessageId types.MessageID `json:"messageId"`

	// RequestId Идентификатор запроса.
	RequestId types.RequestID `json:"requestId"`
}

// NewMessageEvent defines model for NewMessageEvent.
type NewMessageEvent struct {
	// AuthorId Идентификатор автора события.
	AuthorId *types.UserID `json:"authorId,omitempty"`

	// Body Тело события.
	Body string `json:"body"`

	// CreatedAt Дата создания события.
	CreatedAt time.Time `json:"createdAt"`

	// EventId Идентификатор события.
	EventId types.EventID `json:"eventId"`

	// EventType Тип события.
	EventType string `json:"eventType"`

	// IsService Является ли событие системным.
	IsService bool `json:"isService"`

	// MessageId Идентификатор сообщения.
	MessageId types.MessageID `json:"messageId"`

	// RequestId Идентификатор запроса.
	RequestId types.RequestID `json:"requestId"`
}

// AsMessageSentEvent returns the union data inside the Event as a MessageSentEvent
func (t Event) AsMessageSentEvent() (MessageSentEvent, error) {
	var body MessageSentEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMessageSentEvent overwrites any union data inside the Event as the provided MessageSentEvent
func (t *Event) FromMessageSentEvent(v MessageSentEvent) error {
	v.EventType = "MessageSentEvent"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMessageSentEvent performs a merge with any union data inside the Event, using the provided MessageSentEvent
func (t *Event) MergeMessageSentEvent(v MessageSentEvent) error {
	v.EventType = "MessageSentEvent"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsMessageBlockedEvent returns the union data inside the Event as a MessageBlockedEvent
func (t Event) AsMessageBlockedEvent() (MessageBlockedEvent, error) {
	var body MessageBlockedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMessageBlockedEvent overwrites any union data inside the Event as the provided MessageBlockedEvent
func (t *Event) FromMessageBlockedEvent(v MessageBlockedEvent) error {
	v.EventType = "MessageBlockedEvent"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMessageBlockedEvent performs a merge with any union data inside the Event, using the provided MessageBlockedEvent
func (t *Event) MergeMessageBlockedEvent(v MessageBlockedEvent) error {
	v.EventType = "MessageBlockedEvent"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsNewMessageEvent returns the union data inside the Event as a NewMessageEvent
func (t Event) AsNewMessageEvent() (NewMessageEvent, error) {
	var body NewMessageEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNewMessageEvent overwrites any union data inside the Event as the provided NewMessageEvent
func (t *Event) FromNewMessageEvent(v NewMessageEvent) error {
	v.EventType = "NewMessageEvent"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNewMessageEvent performs a merge with any union data inside the Event, using the provided NewMessageEvent
func (t *Event) MergeNewMessageEvent(v NewMessageEvent) error {
	v.EventType = "NewMessageEvent"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

// AsMessageId returns the union data inside the Event as a MessageId
func (t Event) AsMessageId() (MessageId, error) {
	var body MessageId
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMessageId overwrites any union data inside the Event as the provided MessageId
func (t *Event) FromMessageId(v MessageId) error {
	v.EventType = "MessageId"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMessageId performs a merge with any union data inside the Event, using the provided MessageId
func (t *Event) MergeMessageId(v MessageId) error {
	v.EventType = "MessageId"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(t.union, b)
	t.union = merged
	return err
}

func (t Event) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"eventType"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t Event) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "MessageBlockedEvent":
		return t.AsMessageBlockedEvent()
	case "MessageId":
		return t.AsMessageId()
	case "MessageSentEvent":
		return t.AsMessageSentEvent()
	case "NewMessageEvent":
		return t.AsNewMessageEvent()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t Event) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Event) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xWzW7bRhB+FWJaoBdaVNpLwFsS98coGgN1ewp8WJEjaePlLrs7lGsYBGKjlyIHX3ro",
	"uS9QNYgQoU6UVxi+UbFLJpJiopBbBMlJy/2Zb75vZj7oHDJTlEajJgfpObhsioUIy3tKfTnz+9+IGX4l",
	"UeVhu7SmREsSwxf6Gwe5X+boMitLkkZDCvw7P+cFv2ouedn8wkv+m+fNJa+aJ1FzwSv+q3kajq4GEMPY",
	"2EIQpFBVMocY6KxESMGRlXoCMfy8NzF7siiNpZCCoCmkMJE0rUaDzBTJCWKZCVVIR0k2FbTn0M5khonU",
	"hFYLlfiQDuouVgcQNgeB5cG+Pwx0fgiHNwj9wUt+3ZP8drJ1DAU6Jyb4X1TxoX/1Fz4OZb7rmARtLP5U",
	"obttsfkFz/l184RXzQXPPzyl7zsW+1B3nKTFHNJHb1t5sws2WW8W9vht2mb0GDPyWKGNgjbSa1NILcjY",
	"jZE5eygK/2Qdvo7BaDwcQ/roHD61OIYUPknWE5l045h0hThCTS1MHe/04L4y2Qnmu715iKfds1thHORQ",
	"H/dI2Qm4lnUt5XEdQ1+G6TkIpXbQo8+bfLrvFGUDp23b9xV9XZj3AfJuYf43xraHi4qmxt52ruf8rF3y",
	"/KNz9B8d2ta0RiY/6/XyBV/zahc3zywKwvwe9YT5LcjR8X/Bz3neOve/CZILwj2SBfaBSXfU0uwB+5Of",
	"8XVzxYvmsrloriK+5uUWEC/857K5aC55wS/5VfOUX25wGhmjUOgbxhc02iS6mcdNpzuufQCpx8YnSZKU",
	"P70v9El0VJW+otGDqaDogZKoKWobEGKYoXUtldmd4HwlalFKSOGLwZ3BEOLQBaEjE0fVyC8m2CP7AUWV",
	"QxeNjY0mqNEKknoSBaNxg+iQpmhPpcNIUpQbdPoz8ir4lhc+hO90+BrpyIN4KVxptGtn4fPh0P9kRtOb",
	"SStLJbPwMHnsfAJv/iXtPoedn7bKbZM5/BbqOuz7BkfrQrDtO/s4Q2XKwsvZ3oIYKqsghVOXJokymVBT",
	"4yi9O7w7TE6dh/onAAD//1s/i3PaCQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
