// Code generated by options-gen. DO NOT EDIT.
package serverdebug

import (
	fmt461e464ebed9 "fmt"

	"github.com/getkin/kin-openapi/openapi3"
	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
	"go.uber.org/zap/zapcore"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	addr string,
	clientSchema *openapi3.T,
	managerSchema *openapi3.T,
	eventsSchema *openapi3.T,
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from field tag (if present)

	o.addr = addr
	o.clientSchema = clientSchema
	o.managerSchema = managerSchema
	o.eventsSchema = eventsSchema

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithLvlSetter(opt func(level zapcore.Level)) OptOptionsSetter {
	return func(o *Options) {
		o.lvlSetter = opt
	}
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("addr", _validate_Options_addr(o)))
	errs.Add(errors461e464ebed9.NewValidationError("clientSchema", _validate_Options_clientSchema(o)))
	errs.Add(errors461e464ebed9.NewValidationError("managerSchema", _validate_Options_managerSchema(o)))
	errs.Add(errors461e464ebed9.NewValidationError("eventsSchema", _validate_Options_eventsSchema(o)))
	return errs.AsError()
}

func _validate_Options_addr(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.addr, "required,hostname_port"); err != nil {
		return fmt461e464ebed9.Errorf("field `addr` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_clientSchema(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.clientSchema, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `clientSchema` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_managerSchema(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.managerSchema, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `managerSchema` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_eventsSchema(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.eventsSchema, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `eventsSchema` did not pass the test: %w", err)
	}
	return nil
}
