[global]
env = "dev"

[log]
level = "info"

[servers]
[servers.debug]
addr = ":8079"
[servers.client]
addr = ":8080"
allow_origins = ["http://localhost:3011", "http://localhost:3000"]
swagger_file = "api/client.v1.swagger.yml"


[sentry]
dsn = "http://654e05334c5f46aeb8689308b865f8c9@127.0.0.1:9000/2"
