[global]
env = "dev"

[log]
level = "info"

[servers]
[servers.debug]
addr = ":8079"

[servers.client]
addr = ":8080"
allow_origins = ["http://localhost:3011", "http://localhost:3000"]
sec_ws_protocol = "chat-service-protocol"
[servers.client.required_access]
resource = "chat-ui-client"
role = "support-chat-client"

[servers.manager]
addr = ":8081"
allow_origins = ["http://localhost:3011", "http://localhost:3001"]
sec_ws_protocol = "chat-service-protocol"
[servers.manager.required_access]
resource = "chat-ui-manager"
role = "support-chat-manager"


[sentry]
dsn = "http://654e05334c5f46aeb8689308b865f8c9@127.0.0.1:9000/2"

[clients]
[clients.keycloak]
base_path = "http://localhost:3010"
realm = "Bank"
client_id = "chat-service"
client_secret = "qwerrqwerqwerqwetqwerqwer"
debug_mode = false

[postgres]
address = "localhost:5432"
password = "qwerty"
database = "chat"
username = "postgres"
debug = true


[services.outbox]
workers = 2
idle_time = "1s"
reserve_for = "5m"

[services.manager_load]
max_problems_at_same_time = 5

[services.afc_verdicts_processor]
backoff_initial_interval = "100ms"
backoff_max_elapsed_time = "5s"
brokers = ["localhost:9092"]
consumers = 3
consumer_group = "afc-verdicts-processor"
verdicts_topic = "afc.verdicts"
verdicts_signing_public_key = """
-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQClo5ZMkzqYf290prGoy3LWj9eA
O1RID0LpQTODlFzqhL0pGvRpGAZWGncd3+g0ADnJnK06hmre83jOfj47xziuVBka
VZmMBL/tuDxpShXM7fWBFccGHNkj821Eojt54Rc7ivHXplXwiqVwguEIuF8VeSIb
u/BF2lE3m26vhaJ7mQIDAQAB
-----END PUBLIC KEY-----
"""


[services.msg_producer]
brokers = ["localhost:9092"]
topic = "chat.messages"
batch_size = 1
encrypt_key = "51655468576D5A7134743777397A2443"
